### PR TITLE
gstreamer-tests: fix capturetest script issue

### PR DESCRIPTION
**Pull request by ichergui**
Signed-off-by: Ilies CHERGUI <ilies.chergui@gmail.com>

### CODE REVIEW

**Comment by ichergui** [comment]
Here the [issue](https://github.com/OE4T/tegra-demo-distro/issues/139) for more detail.

**Comment by madisongh** [comment]
The fix looks fine, but could you target this for master or dunfell instead of the WIP branch?   Thanks!

**Comment by ichergui** [comment]
> The fix looks fine, but could you target this for master or dunfell instead of the WIP branch? Thanks!

Yes, will do it

**Comment by ichergui** [comment]
Decline this PR, will create new one for master branch

**Pull request closed without merging**
