### PR TITLE
Master+tegrademo mender

### PR DESCRIPTION
**Pull request by kekiefer**
This adds support for mender in a distro named 'tegrademo-mender'

### CODE REVIEW

**Comment by kekiefer** [comment]
@madisongh for the life of me I can't unravel why I'm getting a basehash change when it reparses an image recipe's `do_image_mender` task. It seems like things are getting expanded inconsistently when `do_image_mender` gets reparsed, but I'm at a loss as to why this would be happening.

This task uses the variable `MENDER_ARTIFACT_NAME` derived from `BUILDNAME` derived from `DISTRO_VERSION`, which has `DATE` in it, but the `DISTRO_VERSION[vardepsexclude] = "DATE"`, as it should.

I would appreciate any insight you could offer here.

```
~/tegra/tegra-demo-distro$ bitbake-diffsigs -t core-image-base do_image_mender
NOTE: Starting bitbake server...
basehash changed from 1d9241cda856177754c87014fe999df8cd16a0a51d03cd50c5c81f74e390e98d to c734d46d7a25c48d701d7408eb9b4c0ddcd9b9211a46a7517f9556be22a55342
Variable do_image_mender value changed:
@@ -1,6 +1,6 @@
 	    set -x
 
-    if [ -z "core-image-base_3.1+snapshot-20200914${DISTRO_LAYER_BUILDTAG}" ]; then
+    if [ -z "core-image-base_3.1+snapshot-${DATE}${DISTRO_LAYER_BUILDTAG}" ]; then
         bbfatal "Need to define MENDER_ARTIFACT_NAME variable."
     fi
 
@@ -65,7 +65,7 @@
     fi
 
     mender-artifact write rootfs-image \
-        -n core-image-base_3.1+snapshot-20200914${DISTRO_LAYER_BUILDTAG} \
+        -n core-image-base_3.1+snapshot-${DATE}${DISTRO_LAYER_BUILDTAG} \
         $extra_args \
         $image_flag ${TMPDIR}/work/jetson_tx2-oe4t-linux/core-image-base/1.0-r0/deploy-core-image-base-image-complete/core-image-base-jetson-tx2.ext4 \
          \
```

**Comment by madisongh** [comment]
Yeah, I've run into this before. It's an artifact of how the image type/conversion dependencies are generated in the anonymous python block at the end of `image.bbclass`.  The command variables/functions are expanded immediately as the dependencies are created, so any variable references in those functions whose expanded values are non-deterministic have to be explicitly added to `IMAGE_CMD_mender[vardepsexclude]` - recursive exclusions don't work.

So you can either exclude the DATE reference from DISTRO_VERSION, or add MENDER_ARTIFACT_VERSION to the vardepsexclude... I have tended to go with the former approach, since it requires fewer workaround additions and is more in line with how reproducible builds should work.

**Comment by kekiefer** [comment]
@madisongh thanks, that did the trick. I like the snapshot date in the version, but also would rather avoid a bunch of appends on the python tasks to have it. I factored out a `DISTRO_VERSION_BASE` from tegrademo to leverage for tegrademo-mender, which omits the date.

**Comment by madisongh** [comment]
@kekiefer So is this ready to go in, or did you want to hold off until your meta-mender-community changes make it upstream?

**Comment by kekiefer** [comment]
This is ready to go. I thought it best to leave master pointing at our fork so we can address issues as they come up. Dunfell will wait for upstream.

**Comment by madisongh** [comment]
Great.  Could you rebase on top of master latest?

**Comment by kekiefer** [comment]
Done

**Pull request merged**
